{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-splashscreen",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0-rc01.aar",
          "url": "core-splashscreen-1.0.0-rc01.aar",
          "size": 35235,
          "sha512": "65f5624babed65c6888c0edcecbcba3231cea5cc8677d31270686a001d738fe5c42144c91c993d36c4e3f251a74ba265be2400125682cee8a6d899d4efda6ba5",
          "sha256": "bf09de98143e1d68aa4054e6a8fbcbd204cb4ec0c4d6c189c5612dd63eb0a80a",
          "sha1": "b7a8ee4cd05327420d9236fed82882447ea18173",
          "md5": "a099943ada06777026798f871cf25ae4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0-rc01.aar",
          "url": "core-splashscreen-1.0.0-rc01.aar",
          "size": 35235,
          "sha512": "65f5624babed65c6888c0edcecbcba3231cea5cc8677d31270686a001d738fe5c42144c91c993d36c4e3f251a74ba265be2400125682cee8a6d899d4efda6ba5",
          "sha256": "bf09de98143e1d68aa4054e6a8fbcbd204cb4ec0c4d6c189c5612dd63eb0a80a",
          "sha1": "b7a8ee4cd05327420d9236fed82882447ea18173",
          "md5": "a099943ada06777026798f871cf25ae4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-splashscreen-1.0.0-rc01-sources.jar",
          "url": "core-splashscreen-1.0.0-rc01-sources.jar",
          "size": 11458,
          "sha512": "758509ae4c596c8e9262c0bc930bf186b98778dc0a50f575e2e124920eaae5c4f38e66aaf79198cc3ef2021e7f9cc1bf2cb20227e8c9d8e9cdf46efcc9e7a576",
          "sha256": "f8c16e2b159971feed61d4c12b0fbf53da91f99f855cb893e5a8f2b67772907f",
          "sha1": "e033216357e9111d8d520996527bbd098bd81a66",
          "md5": "f0dddaf82ac1dc7148f9a97fe7919ad6"
        }
      ]
    }
  ]
}