{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-splashscreen",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0-beta02.aar",
          "url": "core-splashscreen-1.0.0-beta02.aar",
          "size": 35281,
          "sha512": "b58d986dcc10c7f86e5801e44623e7f03f85d66ab63e9e1d0d58a420767f039b661eb1130ab3854f6189f18b2acdaa2af10f0220134e98ec0a91fccf16070bd0",
          "sha256": "0421263ba390e58e5ccb05de2714814ded57246135c0d970181ed954d8bfdcf9",
          "sha1": "98d1bce5117f604c72e280bbdce6292d29fc9099",
          "md5": "9903400e55bb22006260cd9380456b03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-splashscreen-1.0.0-beta02.aar",
          "url": "core-splashscreen-1.0.0-beta02.aar",
          "size": 35281,
          "sha512": "b58d986dcc10c7f86e5801e44623e7f03f85d66ab63e9e1d0d58a420767f039b661eb1130ab3854f6189f18b2acdaa2af10f0220134e98ec0a91fccf16070bd0",
          "sha256": "0421263ba390e58e5ccb05de2714814ded57246135c0d970181ed954d8bfdcf9",
          "sha1": "98d1bce5117f604c72e280bbdce6292d29fc9099",
          "md5": "9903400e55bb22006260cd9380456b03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-splashscreen-1.0.0-beta02-sources.jar",
          "url": "core-splashscreen-1.0.0-beta02-sources.jar",
          "size": 11458,
          "sha512": "758509ae4c596c8e9262c0bc930bf186b98778dc0a50f575e2e124920eaae5c4f38e66aaf79198cc3ef2021e7f9cc1bf2cb20227e8c9d8e9cdf46efcc9e7a576",
          "sha256": "f8c16e2b159971feed61d4c12b0fbf53da91f99f855cb893e5a8f2b67772907f",
          "sha1": "e033216357e9111d8d520996527bbd098bd81a66",
          "md5": "f0dddaf82ac1dc7148f9a97fe7919ad6"
        }
      ]
    }
  ]
}